export const I18N = {
  en: {
    meta: {
      title: "Gaoussou Diarra — Portfolio",
      desc: "Portfolio of Gaoussou Diarra — Web & Mobile Developer (HTML, CSS, JS, Angular, PHP/Laravel, MySQL, React, Flutter, Java, Spring Boot).",
    },
    nav: {
      about: "About",
      skills: "Skills",
      projects: "Projects",
      experience: "Experience",
      education: "Education",
      languages: "Languages",
      contact: "Contact",
    },
    hero: {
      title: "Web & Mobile Developer",
    },
    about: {
      title: "About",
      p1: "Hello! I’m <strong>Gaoussou Diarra</strong>, I’m a passionate developer who thrives on turning ideas into clean, reliable, and impactful products. I enjoy working across the stack—whether it’s crafting smooth web experiences or building intuitive mobile apps.",
      p2: "Fluent in French & English. Open to internships, freelance or full-time roles.",
      traits: [
        "Creativity",
        "Perseverance",
        "Curiosity",
        "Collaboration",
        "Self-taught",
        "Interpersonal",
      ],
    },
    skills: {
      title: "Skills",
      tip: "Tip: click any skill to filter projects that match it.",
    },
    projects: {
      title: "Projects",
      searchPH: "Search projects by name, tag or description…",
      empty: "No projects match your search/filter.",
      view: "View",
      more: "View more",
      less: "View less",
    },
    exp: { title: "Experience" },
    edu: { title: "Education" },
    langs: { title: "Languages" },
    experience: [
      {
        title: "Web/Mobile Developer — Fidelity",
        period: "Oct 2023 – Jun 2025 · Casablanca (Remote)",
        desc: "Support on web & mobile features, UI improvements, and marketplace flows.",
      },
      {
        title: "Web Development Intern — Aplika Technology",
        period: "Jul – Sep 2023 · Mali",
        desc: "Front-end components, site enhancements and documentation.",
      },
    ],
    education: [
      {
        title: "Bachelor's Degree - Computer Science",
        period: "Université Hassan II (Morocco) · Sep 2023 – Present",
      },
      {
        title: "English & TOEFL Proficiency",
        period: "The Modern English School (Ghana) · Nov 2022 – May 2023",
      },
      {
        title: "High School Diploma — Exact Sciences",
        period: "2020 – 2021",
      },
    ],
    languages: [
      { name: "French", level: "Fluent", percent: 95 },
      { name: "English", level: "Fluent", percent: 90 },
      { name: "Arabic", level: "Enhancing", percent: 55 },
      { name: "Japanese", level: "Fundamental", percent: 30 },
      { name: "Bambara", level: "Indigenous", percent: 100 },
    ],
    contact: {
      title: "Contact",
      emailLbl: "Email:",
      phoneLbl: "Phone:",
      locationLbl: "Location:",
      emailMe: "Email me",
      quickSend: "Quick send",
      formPHEmail: "Your email",
      formPHMsg: "Your message",
      formNote: "Reach out to me by filling the form ☝️",
    },
    footer: { copy: "Portfolio project" },
    toggles: { theme: "Toggle theme", langBtn: "🇫🇷 FR" },
  },
  fr: {
    meta: {
      title: "Gaoussou Diarra — Portfolio",
      desc: "Portfolio de Gaoussou Diarra — Développeur Web & Mobile (HTML, CSS, JS, Angular, PHP/Laravel, MySQL, React, Flutter, Java, Spring Boot).",
    },
    nav: {
      about: "À propos",
      skills: "Compétences",
      projects: "Projets",
      experience: "Expérience",
      education: "Éducation",
      languages: "Langues",
      contact: "Contact",
    },
    hero: {
      title: "Développeur Web & Mobile",
    },
    about: {
      title: "À propos",
      p1: "Bonjour ! Je suis <strong>Gaoussou Diarra</strong>, un développeur passionné qui aime transformer les idées en produits propres, fiables et impactants. J'apprécie travailler sur toute la stack — que ce soit pour créer des expériences web fluides ou développer des applications mobiles intuitives.",
      p2: "Français & anglais courants. Ouvert aux stages, missions freelance et postes à temps plein.",
      traits: [
        "Créativité",
        "Persévérance",
        "Curiosité",
        "Collaboration",
        "Autodidacte",
        "Relationnel",
      ],
    },
    skills: {
      title: "Compétences",
      tip: "Astuce : cliquez une compétence pour filtrer les projets correspondants.",
    },
    projects: {
      title: "Projets",
      searchPH: "Rechercher des projets par nom, tag ou description…",
      empty: "Aucun projet ne correspond à votre recherche/filtre.",
      view: "Voir",
      more: "Voir plus",
      less: "Voir moins",
    },
    exp: { title: "Expérience" },
    edu: { title: "Éducation" },
    langs: { title: "Langues" },
    experience: [
      {
        title: "Développeur web/mobile — Fidelity",
        period: "Oct 2023 – Juin 2025 · Casablanca (À distance)",
        desc: "Support sur des fonctionnalités web & mobile, améliorations UI et parcours marketplace.",
      },
      {
        title: "Stagiaire en développement web — Aplika Technology",
        period: "Juil – Sep 2023 · Mali",
        desc: "Composants front-end, améliorations du site et documentation.",
      },
    ],
    education: [
      {
        title: "Licence en Informatique",
        period: "Université Hassan II (Maroc) · Sep 2023 – Présent",
      },
      {
        title: "Anglais & TOEFL",
        period: "The Modern English School (Ghana) · Nov 2022 – Mai 2023",
      },
      {
        title: "Diplôme de Baccalauréat — Sciences exactes",
        period: "2020 – 2021",
      },
    ],
    languages: [
      { name: "Français", level: "Courant", percent: 95 },
      { name: "Anglais", level: "Courant", percent: 90 },
      { name: "Arabe", level: "En amélioration", percent: 55 },
      { name: "Japonais", level: "Notions", percent: 30 },
      { name: "Bambara", level: "Langue maternelle", percent: 100 },
    ],
    contact: {
      title: "Contact",
      emailLbl: "Email :",
      phoneLbl: "Téléphone :",
      locationLbl: "Localisation :",
      emailMe: "M’écrire",
      formPHEmail: "Votre email",
      formPHMsg: "Votre message",
      formNote: "Contactez-moi via le formulaire ☝️",
    },
    footer: { copy: "Projet de portfolio" },
    toggles: { theme: "Changer de thème", langBtn: "🇬🇧 EN" },
  },
};
